// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ConversationService.proto

package com_salty_protos

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetAllConversationReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAllConversationReq) Reset()         { *m = GetAllConversationReq{} }
func (m *GetAllConversationReq) String() string { return proto.CompactTextString(m) }
func (*GetAllConversationReq) ProtoMessage()    {}
func (*GetAllConversationReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf2ec427efda0568, []int{0}
}

func (m *GetAllConversationReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAllConversationReq.Unmarshal(m, b)
}
func (m *GetAllConversationReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAllConversationReq.Marshal(b, m, deterministic)
}
func (m *GetAllConversationReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAllConversationReq.Merge(m, src)
}
func (m *GetAllConversationReq) XXX_Size() int {
	return xxx_messageInfo_GetAllConversationReq.Size(m)
}
func (m *GetAllConversationReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAllConversationReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetAllConversationReq proto.InternalMessageInfo

type GetAllConversationResp struct {
	ConversationArr      []*Conversation `protobuf:"bytes,1,rep,name=conversationArr,proto3" json:"conversationArr,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *GetAllConversationResp) Reset()         { *m = GetAllConversationResp{} }
func (m *GetAllConversationResp) String() string { return proto.CompactTextString(m) }
func (*GetAllConversationResp) ProtoMessage()    {}
func (*GetAllConversationResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf2ec427efda0568, []int{1}
}

func (m *GetAllConversationResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAllConversationResp.Unmarshal(m, b)
}
func (m *GetAllConversationResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAllConversationResp.Marshal(b, m, deterministic)
}
func (m *GetAllConversationResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAllConversationResp.Merge(m, src)
}
func (m *GetAllConversationResp) XXX_Size() int {
	return xxx_messageInfo_GetAllConversationResp.Size(m)
}
func (m *GetAllConversationResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAllConversationResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetAllConversationResp proto.InternalMessageInfo

func (m *GetAllConversationResp) GetConversationArr() []*Conversation {
	if m != nil {
		return m.ConversationArr
	}
	return nil
}

type GetConversationDetailReq struct {
	ConversationId       string                        `protobuf:"bytes,1,opt,name=conversationId,proto3" json:"conversationId,omitempty"`
	ConversationType     Conversation_ConversationType `protobuf:"varint,2,opt,name=conversationType,proto3,enum=com.salty.protos.Conversation_ConversationType" json:"conversationType,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *GetConversationDetailReq) Reset()         { *m = GetConversationDetailReq{} }
func (m *GetConversationDetailReq) String() string { return proto.CompactTextString(m) }
func (*GetConversationDetailReq) ProtoMessage()    {}
func (*GetConversationDetailReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf2ec427efda0568, []int{2}
}

func (m *GetConversationDetailReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetConversationDetailReq.Unmarshal(m, b)
}
func (m *GetConversationDetailReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetConversationDetailReq.Marshal(b, m, deterministic)
}
func (m *GetConversationDetailReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetConversationDetailReq.Merge(m, src)
}
func (m *GetConversationDetailReq) XXX_Size() int {
	return xxx_messageInfo_GetConversationDetailReq.Size(m)
}
func (m *GetConversationDetailReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetConversationDetailReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetConversationDetailReq proto.InternalMessageInfo

func (m *GetConversationDetailReq) GetConversationId() string {
	if m != nil {
		return m.ConversationId
	}
	return ""
}

func (m *GetConversationDetailReq) GetConversationType() Conversation_ConversationType {
	if m != nil {
		return m.ConversationType
	}
	return Conversation_NONE
}

type GetConversationDetailResp struct {
	Conversation         *Conversation `protobuf:"bytes,1,opt,name=conversation,proto3" json:"conversation,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *GetConversationDetailResp) Reset()         { *m = GetConversationDetailResp{} }
func (m *GetConversationDetailResp) String() string { return proto.CompactTextString(m) }
func (*GetConversationDetailResp) ProtoMessage()    {}
func (*GetConversationDetailResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf2ec427efda0568, []int{3}
}

func (m *GetConversationDetailResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetConversationDetailResp.Unmarshal(m, b)
}
func (m *GetConversationDetailResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetConversationDetailResp.Marshal(b, m, deterministic)
}
func (m *GetConversationDetailResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetConversationDetailResp.Merge(m, src)
}
func (m *GetConversationDetailResp) XXX_Size() int {
	return xxx_messageInfo_GetConversationDetailResp.Size(m)
}
func (m *GetConversationDetailResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetConversationDetailResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetConversationDetailResp proto.InternalMessageInfo

func (m *GetConversationDetailResp) GetConversation() *Conversation {
	if m != nil {
		return m.Conversation
	}
	return nil
}

type RemoveConversationReq struct {
	ConversationId       string                        `protobuf:"bytes,1,opt,name=conversationId,proto3" json:"conversationId,omitempty"`
	ConversationType     Conversation_ConversationType `protobuf:"varint,2,opt,name=conversationType,proto3,enum=com.salty.protos.Conversation_ConversationType" json:"conversationType,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *RemoveConversationReq) Reset()         { *m = RemoveConversationReq{} }
func (m *RemoveConversationReq) String() string { return proto.CompactTextString(m) }
func (*RemoveConversationReq) ProtoMessage()    {}
func (*RemoveConversationReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf2ec427efda0568, []int{4}
}

func (m *RemoveConversationReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveConversationReq.Unmarshal(m, b)
}
func (m *RemoveConversationReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveConversationReq.Marshal(b, m, deterministic)
}
func (m *RemoveConversationReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveConversationReq.Merge(m, src)
}
func (m *RemoveConversationReq) XXX_Size() int {
	return xxx_messageInfo_RemoveConversationReq.Size(m)
}
func (m *RemoveConversationReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveConversationReq.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveConversationReq proto.InternalMessageInfo

func (m *RemoveConversationReq) GetConversationId() string {
	if m != nil {
		return m.ConversationId
	}
	return ""
}

func (m *RemoveConversationReq) GetConversationType() Conversation_ConversationType {
	if m != nil {
		return m.ConversationType
	}
	return Conversation_NONE
}

type RemoveConversationResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveConversationResp) Reset()         { *m = RemoveConversationResp{} }
func (m *RemoveConversationResp) String() string { return proto.CompactTextString(m) }
func (*RemoveConversationResp) ProtoMessage()    {}
func (*RemoveConversationResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf2ec427efda0568, []int{5}
}

func (m *RemoveConversationResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveConversationResp.Unmarshal(m, b)
}
func (m *RemoveConversationResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveConversationResp.Marshal(b, m, deterministic)
}
func (m *RemoveConversationResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveConversationResp.Merge(m, src)
}
func (m *RemoveConversationResp) XXX_Size() int {
	return xxx_messageInfo_RemoveConversationResp.Size(m)
}
func (m *RemoveConversationResp) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveConversationResp.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveConversationResp proto.InternalMessageInfo

type ClearConversationMessageReq struct {
	ConversationId       string                        `protobuf:"bytes,1,opt,name=conversationId,proto3" json:"conversationId,omitempty"`
	ConversationType     Conversation_ConversationType `protobuf:"varint,2,opt,name=conversationType,proto3,enum=com.salty.protos.Conversation_ConversationType" json:"conversationType,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *ClearConversationMessageReq) Reset()         { *m = ClearConversationMessageReq{} }
func (m *ClearConversationMessageReq) String() string { return proto.CompactTextString(m) }
func (*ClearConversationMessageReq) ProtoMessage()    {}
func (*ClearConversationMessageReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf2ec427efda0568, []int{6}
}

func (m *ClearConversationMessageReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClearConversationMessageReq.Unmarshal(m, b)
}
func (m *ClearConversationMessageReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClearConversationMessageReq.Marshal(b, m, deterministic)
}
func (m *ClearConversationMessageReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClearConversationMessageReq.Merge(m, src)
}
func (m *ClearConversationMessageReq) XXX_Size() int {
	return xxx_messageInfo_ClearConversationMessageReq.Size(m)
}
func (m *ClearConversationMessageReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ClearConversationMessageReq.DiscardUnknown(m)
}

var xxx_messageInfo_ClearConversationMessageReq proto.InternalMessageInfo

func (m *ClearConversationMessageReq) GetConversationId() string {
	if m != nil {
		return m.ConversationId
	}
	return ""
}

func (m *ClearConversationMessageReq) GetConversationType() Conversation_ConversationType {
	if m != nil {
		return m.ConversationType
	}
	return Conversation_NONE
}

type ClearConversationMessageResp struct {
	Conversation         *Conversation `protobuf:"bytes,1,opt,name=conversation,proto3" json:"conversation,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ClearConversationMessageResp) Reset()         { *m = ClearConversationMessageResp{} }
func (m *ClearConversationMessageResp) String() string { return proto.CompactTextString(m) }
func (*ClearConversationMessageResp) ProtoMessage()    {}
func (*ClearConversationMessageResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf2ec427efda0568, []int{7}
}

func (m *ClearConversationMessageResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClearConversationMessageResp.Unmarshal(m, b)
}
func (m *ClearConversationMessageResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClearConversationMessageResp.Marshal(b, m, deterministic)
}
func (m *ClearConversationMessageResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClearConversationMessageResp.Merge(m, src)
}
func (m *ClearConversationMessageResp) XXX_Size() int {
	return xxx_messageInfo_ClearConversationMessageResp.Size(m)
}
func (m *ClearConversationMessageResp) XXX_DiscardUnknown() {
	xxx_messageInfo_ClearConversationMessageResp.DiscardUnknown(m)
}

var xxx_messageInfo_ClearConversationMessageResp proto.InternalMessageInfo

func (m *ClearConversationMessageResp) GetConversation() *Conversation {
	if m != nil {
		return m.Conversation
	}
	return nil
}

type UpdateConversationTitleReq struct {
	ConversationId       string                        `protobuf:"bytes,1,opt,name=conversationId,proto3" json:"conversationId,omitempty"`
	ConversationType     Conversation_ConversationType `protobuf:"varint,2,opt,name=conversationType,proto3,enum=com.salty.protos.Conversation_ConversationType" json:"conversationType,omitempty"`
	Title                string                        `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *UpdateConversationTitleReq) Reset()         { *m = UpdateConversationTitleReq{} }
func (m *UpdateConversationTitleReq) String() string { return proto.CompactTextString(m) }
func (*UpdateConversationTitleReq) ProtoMessage()    {}
func (*UpdateConversationTitleReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf2ec427efda0568, []int{8}
}

func (m *UpdateConversationTitleReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateConversationTitleReq.Unmarshal(m, b)
}
func (m *UpdateConversationTitleReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateConversationTitleReq.Marshal(b, m, deterministic)
}
func (m *UpdateConversationTitleReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateConversationTitleReq.Merge(m, src)
}
func (m *UpdateConversationTitleReq) XXX_Size() int {
	return xxx_messageInfo_UpdateConversationTitleReq.Size(m)
}
func (m *UpdateConversationTitleReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateConversationTitleReq.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateConversationTitleReq proto.InternalMessageInfo

func (m *UpdateConversationTitleReq) GetConversationId() string {
	if m != nil {
		return m.ConversationId
	}
	return ""
}

func (m *UpdateConversationTitleReq) GetConversationType() Conversation_ConversationType {
	if m != nil {
		return m.ConversationType
	}
	return Conversation_NONE
}

func (m *UpdateConversationTitleReq) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

type UpdateConversationTitleResp struct {
	Conversation         *Conversation `protobuf:"bytes,1,opt,name=conversation,proto3" json:"conversation,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *UpdateConversationTitleResp) Reset()         { *m = UpdateConversationTitleResp{} }
func (m *UpdateConversationTitleResp) String() string { return proto.CompactTextString(m) }
func (*UpdateConversationTitleResp) ProtoMessage()    {}
func (*UpdateConversationTitleResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf2ec427efda0568, []int{9}
}

func (m *UpdateConversationTitleResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateConversationTitleResp.Unmarshal(m, b)
}
func (m *UpdateConversationTitleResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateConversationTitleResp.Marshal(b, m, deterministic)
}
func (m *UpdateConversationTitleResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateConversationTitleResp.Merge(m, src)
}
func (m *UpdateConversationTitleResp) XXX_Size() int {
	return xxx_messageInfo_UpdateConversationTitleResp.Size(m)
}
func (m *UpdateConversationTitleResp) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateConversationTitleResp.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateConversationTitleResp proto.InternalMessageInfo

func (m *UpdateConversationTitleResp) GetConversation() *Conversation {
	if m != nil {
		return m.Conversation
	}
	return nil
}

type UpdateConversationTopReq struct {
	ConversationId       string                        `protobuf:"bytes,1,opt,name=conversationId,proto3" json:"conversationId,omitempty"`
	ConversationType     Conversation_ConversationType `protobuf:"varint,2,opt,name=conversationType,proto3,enum=com.salty.protos.Conversation_ConversationType" json:"conversationType,omitempty"`
	IsTop                bool                          `protobuf:"varint,3,opt,name=isTop,proto3" json:"isTop,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *UpdateConversationTopReq) Reset()         { *m = UpdateConversationTopReq{} }
func (m *UpdateConversationTopReq) String() string { return proto.CompactTextString(m) }
func (*UpdateConversationTopReq) ProtoMessage()    {}
func (*UpdateConversationTopReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf2ec427efda0568, []int{10}
}

func (m *UpdateConversationTopReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateConversationTopReq.Unmarshal(m, b)
}
func (m *UpdateConversationTopReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateConversationTopReq.Marshal(b, m, deterministic)
}
func (m *UpdateConversationTopReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateConversationTopReq.Merge(m, src)
}
func (m *UpdateConversationTopReq) XXX_Size() int {
	return xxx_messageInfo_UpdateConversationTopReq.Size(m)
}
func (m *UpdateConversationTopReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateConversationTopReq.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateConversationTopReq proto.InternalMessageInfo

func (m *UpdateConversationTopReq) GetConversationId() string {
	if m != nil {
		return m.ConversationId
	}
	return ""
}

func (m *UpdateConversationTopReq) GetConversationType() Conversation_ConversationType {
	if m != nil {
		return m.ConversationType
	}
	return Conversation_NONE
}

func (m *UpdateConversationTopReq) GetIsTop() bool {
	if m != nil {
		return m.IsTop
	}
	return false
}

type UpdateConversationTopResp struct {
	Conversation         *Conversation `protobuf:"bytes,1,opt,name=conversation,proto3" json:"conversation,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *UpdateConversationTopResp) Reset()         { *m = UpdateConversationTopResp{} }
func (m *UpdateConversationTopResp) String() string { return proto.CompactTextString(m) }
func (*UpdateConversationTopResp) ProtoMessage()    {}
func (*UpdateConversationTopResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf2ec427efda0568, []int{11}
}

func (m *UpdateConversationTopResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateConversationTopResp.Unmarshal(m, b)
}
func (m *UpdateConversationTopResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateConversationTopResp.Marshal(b, m, deterministic)
}
func (m *UpdateConversationTopResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateConversationTopResp.Merge(m, src)
}
func (m *UpdateConversationTopResp) XXX_Size() int {
	return xxx_messageInfo_UpdateConversationTopResp.Size(m)
}
func (m *UpdateConversationTopResp) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateConversationTopResp.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateConversationTopResp proto.InternalMessageInfo

func (m *UpdateConversationTopResp) GetConversation() *Conversation {
	if m != nil {
		return m.Conversation
	}
	return nil
}

type UpdateNotificationStatusReq struct {
	ConversationId       string                          `protobuf:"bytes,1,opt,name=conversationId,proto3" json:"conversationId,omitempty"`
	ConversationType     Conversation_ConversationType   `protobuf:"varint,2,opt,name=conversationType,proto3,enum=com.salty.protos.Conversation_ConversationType" json:"conversationType,omitempty"`
	NotificationStatus   Conversation_NotificationStatus `protobuf:"varint,3,opt,name=notificationStatus,proto3,enum=com.salty.protos.Conversation_NotificationStatus" json:"notificationStatus,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                        `json:"-"`
	XXX_unrecognized     []byte                          `json:"-"`
	XXX_sizecache        int32                           `json:"-"`
}

func (m *UpdateNotificationStatusReq) Reset()         { *m = UpdateNotificationStatusReq{} }
func (m *UpdateNotificationStatusReq) String() string { return proto.CompactTextString(m) }
func (*UpdateNotificationStatusReq) ProtoMessage()    {}
func (*UpdateNotificationStatusReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf2ec427efda0568, []int{12}
}

func (m *UpdateNotificationStatusReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateNotificationStatusReq.Unmarshal(m, b)
}
func (m *UpdateNotificationStatusReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateNotificationStatusReq.Marshal(b, m, deterministic)
}
func (m *UpdateNotificationStatusReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateNotificationStatusReq.Merge(m, src)
}
func (m *UpdateNotificationStatusReq) XXX_Size() int {
	return xxx_messageInfo_UpdateNotificationStatusReq.Size(m)
}
func (m *UpdateNotificationStatusReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateNotificationStatusReq.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateNotificationStatusReq proto.InternalMessageInfo

func (m *UpdateNotificationStatusReq) GetConversationId() string {
	if m != nil {
		return m.ConversationId
	}
	return ""
}

func (m *UpdateNotificationStatusReq) GetConversationType() Conversation_ConversationType {
	if m != nil {
		return m.ConversationType
	}
	return Conversation_NONE
}

func (m *UpdateNotificationStatusReq) GetNotificationStatus() Conversation_NotificationStatus {
	if m != nil {
		return m.NotificationStatus
	}
	return Conversation_NOTIFY
}

type UpdateNotificationStatusResp struct {
	Conversation         *Conversation `protobuf:"bytes,1,opt,name=conversation,proto3" json:"conversation,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *UpdateNotificationStatusResp) Reset()         { *m = UpdateNotificationStatusResp{} }
func (m *UpdateNotificationStatusResp) String() string { return proto.CompactTextString(m) }
func (*UpdateNotificationStatusResp) ProtoMessage()    {}
func (*UpdateNotificationStatusResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf2ec427efda0568, []int{13}
}

func (m *UpdateNotificationStatusResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateNotificationStatusResp.Unmarshal(m, b)
}
func (m *UpdateNotificationStatusResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateNotificationStatusResp.Marshal(b, m, deterministic)
}
func (m *UpdateNotificationStatusResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateNotificationStatusResp.Merge(m, src)
}
func (m *UpdateNotificationStatusResp) XXX_Size() int {
	return xxx_messageInfo_UpdateNotificationStatusResp.Size(m)
}
func (m *UpdateNotificationStatusResp) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateNotificationStatusResp.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateNotificationStatusResp proto.InternalMessageInfo

func (m *UpdateNotificationStatusResp) GetConversation() *Conversation {
	if m != nil {
		return m.Conversation
	}
	return nil
}

func init() {
	proto.RegisterType((*GetAllConversationReq)(nil), "com.salty.protos.GetAllConversationReq")
	proto.RegisterType((*GetAllConversationResp)(nil), "com.salty.protos.GetAllConversationResp")
	proto.RegisterType((*GetConversationDetailReq)(nil), "com.salty.protos.GetConversationDetailReq")
	proto.RegisterType((*GetConversationDetailResp)(nil), "com.salty.protos.GetConversationDetailResp")
	proto.RegisterType((*RemoveConversationReq)(nil), "com.salty.protos.RemoveConversationReq")
	proto.RegisterType((*RemoveConversationResp)(nil), "com.salty.protos.RemoveConversationResp")
	proto.RegisterType((*ClearConversationMessageReq)(nil), "com.salty.protos.ClearConversationMessageReq")
	proto.RegisterType((*ClearConversationMessageResp)(nil), "com.salty.protos.ClearConversationMessageResp")
	proto.RegisterType((*UpdateConversationTitleReq)(nil), "com.salty.protos.UpdateConversationTitleReq")
	proto.RegisterType((*UpdateConversationTitleResp)(nil), "com.salty.protos.UpdateConversationTitleResp")
	proto.RegisterType((*UpdateConversationTopReq)(nil), "com.salty.protos.UpdateConversationTopReq")
	proto.RegisterType((*UpdateConversationTopResp)(nil), "com.salty.protos.UpdateConversationTopResp")
	proto.RegisterType((*UpdateNotificationStatusReq)(nil), "com.salty.protos.UpdateNotificationStatusReq")
	proto.RegisterType((*UpdateNotificationStatusResp)(nil), "com.salty.protos.UpdateNotificationStatusResp")
}

func init() { proto.RegisterFile("ConversationService.proto", fileDescriptor_cf2ec427efda0568) }

var fileDescriptor_cf2ec427efda0568 = []byte{
	// 458 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x95, 0xdf, 0x6a, 0x14, 0x31,
	0x14, 0xc6, 0xcd, 0x56, 0x45, 0x8f, 0x65, 0x2d, 0xd1, 0xb6, 0xd9, 0xad, 0xc8, 0x92, 0x0b, 0xd9,
	0xab, 0x11, 0xc7, 0x27, 0x68, 0x2b, 0xac, 0x5e, 0xac, 0x94, 0x74, 0xbd, 0xf2, 0x42, 0xb2, 0xd3,
	0xa3, 0x04, 0xa6, 0x93, 0xec, 0x24, 0x2e, 0xf4, 0x01, 0x7c, 0x0b, 0x41, 0xf0, 0x1d, 0xc4, 0x27,
	0xf1, 0x7d, 0x64, 0x66, 0x28, 0xcc, 0xbf, 0xb4, 0x30, 0x9d, 0x8b, 0xb9, 0x3c, 0x27, 0x73, 0xbe,
	0x7c, 0xf9, 0x65, 0x72, 0x0e, 0x4c, 0x4e, 0x75, 0xb2, 0xc5, 0xd4, 0x4a, 0xa7, 0x74, 0x72, 0x8e,
	0xe9, 0x56, 0x45, 0x18, 0x98, 0x54, 0x3b, 0x4d, 0xf7, 0x22, 0x7d, 0x19, 0x58, 0x19, 0xbb, 0xab,
	0x22, 0x61, 0xa7, 0xbb, 0x98, 0x38, 0x75, 0x1d, 0xf2, 0x43, 0xd8, 0x5f, 0xa0, 0x3b, 0x8e, 0xe3,
	0xb2, 0x84, 0xc0, 0x0d, 0x5f, 0xc3, 0x41, 0xdb, 0x82, 0x35, 0xf4, 0x3d, 0x3c, 0x8d, 0x4a, 0xb9,
	0xe3, 0x34, 0x65, 0x64, 0xb6, 0x33, 0x7f, 0x12, 0xbe, 0x0c, 0xea, 0x9b, 0x05, 0x95, 0xe2, 0x7a,
	0x19, 0xff, 0x45, 0x80, 0x2d, 0xd0, 0x95, 0x3f, 0x7a, 0x87, 0x4e, 0xaa, 0x58, 0xe0, 0x86, 0xbe,
	0x82, 0x71, 0xf9, 0xfb, 0x0f, 0x17, 0x8c, 0xcc, 0xc8, 0xfc, 0xb1, 0xa8, 0x65, 0xe9, 0x67, 0xd8,
	0x2b, 0x67, 0x56, 0x57, 0x06, 0xd9, 0x68, 0x46, 0xe6, 0xe3, 0xf0, 0xf5, 0xcd, 0x7e, 0x2a, 0x41,
	0x56, 0x26, 0x1a, 0x42, 0xfc, 0x0b, 0x4c, 0x3c, 0x06, 0xad, 0xa1, 0x27, 0xb0, 0x5b, 0x2e, 0xc8,
	0xfd, 0xdd, 0x4e, 0xa1, 0x52, 0xc3, 0x7f, 0x12, 0xd8, 0x17, 0x78, 0xa9, 0xb7, 0x58, 0xbb, 0x80,
	0x61, 0x9c, 0x9f, 0xc1, 0x41, 0x9b, 0x3b, 0x6b, 0xf8, 0x6f, 0x02, 0x47, 0xa7, 0x31, 0xca, 0xb4,
	0xbc, 0xb2, 0x44, 0x6b, 0xe5, 0x37, 0x1c, 0x8c, 0xfd, 0x35, 0xbc, 0xf0, 0x7b, 0xec, 0xe9, 0x06,
	0xff, 0x12, 0x98, 0x7e, 0x32, 0x17, 0xd2, 0x55, 0x18, 0xad, 0x94, 0x8b, 0x07, 0xc3, 0x81, 0x3e,
	0x87, 0x07, 0x2e, 0x33, 0xc4, 0x76, 0xf2, 0xbd, 0x8b, 0x80, 0x4b, 0x38, 0xf2, 0x1a, 0xef, 0x09,
	0xce, 0x1f, 0x02, 0xac, 0x65, 0x0f, 0x6d, 0x86, 0x84, 0x46, 0xd9, 0x95, 0x36, 0x39, 0x9a, 0x47,
	0xa2, 0x08, 0xb2, 0x77, 0xef, 0xb1, 0xdd, 0x13, 0x98, 0x1f, 0xa3, 0x6b, 0xf8, 0x1f, 0xb5, 0x53,
	0x5f, 0x55, 0x54, 0xf4, 0x6e, 0x27, 0xdd, 0x77, 0x3b, 0x18, 0x36, 0x12, 0x68, 0xd2, 0x70, 0x97,
	0x83, 0x1a, 0x87, 0x6f, 0x6e, 0x91, 0x6f, 0x39, 0x56, 0x8b, 0x58, 0xf6, 0x42, 0xfd, 0x18, 0xfa,
	0x61, 0x1d, 0xfe, 0xbb, 0x0f, 0xcf, 0x5a, 0x26, 0x24, 0x5d, 0x02, 0x6d, 0x8e, 0x38, 0x3a, 0x69,
	0x6a, 0x2f, 0x52, 0x13, 0x09, 0xdc, 0x4c, 0xa7, 0xbe, 0x25, 0x6b, 0xf8, 0x3d, 0x7a, 0x96, 0x8f,
	0xd2, 0xe6, 0xac, 0xe8, 0xae, 0xb8, 0x04, 0xda, 0xec, 0xbe, 0xdd, 0xe5, 0xce, 0x81, 0xf9, 0xba,
	0x61, 0x77, 0x51, 0x01, 0x87, 0x9e, 0x26, 0x72, 0x27, 0x92, 0xad, 0xaf, 0xef, 0x4e, 0x47, 0xf7,
	0xfd, 0x66, 0x9d, 0x45, 0x4f, 0x46, 0x67, 0x64, 0xfd, 0x30, 0x4f, 0xbf, 0xfd, 0x1f, 0x00, 0x00,
	0xff, 0xff, 0x8d, 0x7e, 0xb8, 0xd7, 0x83, 0x09, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ConversationServiceClient is the client API for ConversationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ConversationServiceClient interface {
	//获取所有会话
	GetAllConversation(ctx context.Context, in *GrpcReq, opts ...grpc.CallOption) (*GrpcResp, error)
	//获取某一个会话
	GetConversationDetail(ctx context.Context, in *GrpcReq, opts ...grpc.CallOption) (*GrpcResp, error)
	//删除会话
	RemoveConversation(ctx context.Context, in *GrpcReq, opts ...grpc.CallOption) (*GrpcResp, error)
	//清空会话消息(清空该会话的聊天记录)
	ClearConversationMessage(ctx context.Context, in *GrpcReq, opts ...grpc.CallOption) (*GrpcResp, error)
	//更新会话标题
	UpdateConversationTitle(ctx context.Context, in *GrpcReq, opts ...grpc.CallOption) (*GrpcResp, error)
	//更新会话置顶状态
	UpdateConversationTop(ctx context.Context, in *GrpcReq, opts ...grpc.CallOption) (*GrpcResp, error)
	//更新会话提醒状态
	UpdateNotificationStatus(ctx context.Context, in *GrpcReq, opts ...grpc.CallOption) (*GrpcResp, error)
}

type conversationServiceClient struct {
	cc *grpc.ClientConn
}

func NewConversationServiceClient(cc *grpc.ClientConn) ConversationServiceClient {
	return &conversationServiceClient{cc}
}

func (c *conversationServiceClient) GetAllConversation(ctx context.Context, in *GrpcReq, opts ...grpc.CallOption) (*GrpcResp, error) {
	out := new(GrpcResp)
	err := c.cc.Invoke(ctx, "/com.salty.protos.ConversationService/GetAllConversation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *conversationServiceClient) GetConversationDetail(ctx context.Context, in *GrpcReq, opts ...grpc.CallOption) (*GrpcResp, error) {
	out := new(GrpcResp)
	err := c.cc.Invoke(ctx, "/com.salty.protos.ConversationService/GetConversationDetail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *conversationServiceClient) RemoveConversation(ctx context.Context, in *GrpcReq, opts ...grpc.CallOption) (*GrpcResp, error) {
	out := new(GrpcResp)
	err := c.cc.Invoke(ctx, "/com.salty.protos.ConversationService/RemoveConversation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *conversationServiceClient) ClearConversationMessage(ctx context.Context, in *GrpcReq, opts ...grpc.CallOption) (*GrpcResp, error) {
	out := new(GrpcResp)
	err := c.cc.Invoke(ctx, "/com.salty.protos.ConversationService/ClearConversationMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *conversationServiceClient) UpdateConversationTitle(ctx context.Context, in *GrpcReq, opts ...grpc.CallOption) (*GrpcResp, error) {
	out := new(GrpcResp)
	err := c.cc.Invoke(ctx, "/com.salty.protos.ConversationService/UpdateConversationTitle", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *conversationServiceClient) UpdateConversationTop(ctx context.Context, in *GrpcReq, opts ...grpc.CallOption) (*GrpcResp, error) {
	out := new(GrpcResp)
	err := c.cc.Invoke(ctx, "/com.salty.protos.ConversationService/UpdateConversationTop", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *conversationServiceClient) UpdateNotificationStatus(ctx context.Context, in *GrpcReq, opts ...grpc.CallOption) (*GrpcResp, error) {
	out := new(GrpcResp)
	err := c.cc.Invoke(ctx, "/com.salty.protos.ConversationService/UpdateNotificationStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ConversationServiceServer is the server API for ConversationService service.
type ConversationServiceServer interface {
	//获取所有会话
	GetAllConversation(context.Context, *GrpcReq) (*GrpcResp, error)
	//获取某一个会话
	GetConversationDetail(context.Context, *GrpcReq) (*GrpcResp, error)
	//删除会话
	RemoveConversation(context.Context, *GrpcReq) (*GrpcResp, error)
	//清空会话消息(清空该会话的聊天记录)
	ClearConversationMessage(context.Context, *GrpcReq) (*GrpcResp, error)
	//更新会话标题
	UpdateConversationTitle(context.Context, *GrpcReq) (*GrpcResp, error)
	//更新会话置顶状态
	UpdateConversationTop(context.Context, *GrpcReq) (*GrpcResp, error)
	//更新会话提醒状态
	UpdateNotificationStatus(context.Context, *GrpcReq) (*GrpcResp, error)
}

// UnimplementedConversationServiceServer can be embedded to have forward compatible implementations.
type UnimplementedConversationServiceServer struct {
}

func (*UnimplementedConversationServiceServer) GetAllConversation(ctx context.Context, req *GrpcReq) (*GrpcResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllConversation not implemented")
}
func (*UnimplementedConversationServiceServer) GetConversationDetail(ctx context.Context, req *GrpcReq) (*GrpcResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetConversationDetail not implemented")
}
func (*UnimplementedConversationServiceServer) RemoveConversation(ctx context.Context, req *GrpcReq) (*GrpcResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveConversation not implemented")
}
func (*UnimplementedConversationServiceServer) ClearConversationMessage(ctx context.Context, req *GrpcReq) (*GrpcResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClearConversationMessage not implemented")
}
func (*UnimplementedConversationServiceServer) UpdateConversationTitle(ctx context.Context, req *GrpcReq) (*GrpcResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateConversationTitle not implemented")
}
func (*UnimplementedConversationServiceServer) UpdateConversationTop(ctx context.Context, req *GrpcReq) (*GrpcResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateConversationTop not implemented")
}
func (*UnimplementedConversationServiceServer) UpdateNotificationStatus(ctx context.Context, req *GrpcReq) (*GrpcResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateNotificationStatus not implemented")
}

func RegisterConversationServiceServer(s *grpc.Server, srv ConversationServiceServer) {
	s.RegisterService(&_ConversationService_serviceDesc, srv)
}

func _ConversationService_GetAllConversation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GrpcReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConversationServiceServer).GetAllConversation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/com.salty.protos.ConversationService/GetAllConversation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConversationServiceServer).GetAllConversation(ctx, req.(*GrpcReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConversationService_GetConversationDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GrpcReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConversationServiceServer).GetConversationDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/com.salty.protos.ConversationService/GetConversationDetail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConversationServiceServer).GetConversationDetail(ctx, req.(*GrpcReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConversationService_RemoveConversation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GrpcReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConversationServiceServer).RemoveConversation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/com.salty.protos.ConversationService/RemoveConversation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConversationServiceServer).RemoveConversation(ctx, req.(*GrpcReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConversationService_ClearConversationMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GrpcReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConversationServiceServer).ClearConversationMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/com.salty.protos.ConversationService/ClearConversationMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConversationServiceServer).ClearConversationMessage(ctx, req.(*GrpcReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConversationService_UpdateConversationTitle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GrpcReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConversationServiceServer).UpdateConversationTitle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/com.salty.protos.ConversationService/UpdateConversationTitle",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConversationServiceServer).UpdateConversationTitle(ctx, req.(*GrpcReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConversationService_UpdateConversationTop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GrpcReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConversationServiceServer).UpdateConversationTop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/com.salty.protos.ConversationService/UpdateConversationTop",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConversationServiceServer).UpdateConversationTop(ctx, req.(*GrpcReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConversationService_UpdateNotificationStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GrpcReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConversationServiceServer).UpdateNotificationStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/com.salty.protos.ConversationService/UpdateNotificationStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConversationServiceServer).UpdateNotificationStatus(ctx, req.(*GrpcReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _ConversationService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "com.salty.protos.ConversationService",
	HandlerType: (*ConversationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAllConversation",
			Handler:    _ConversationService_GetAllConversation_Handler,
		},
		{
			MethodName: "GetConversationDetail",
			Handler:    _ConversationService_GetConversationDetail_Handler,
		},
		{
			MethodName: "RemoveConversation",
			Handler:    _ConversationService_RemoveConversation_Handler,
		},
		{
			MethodName: "ClearConversationMessage",
			Handler:    _ConversationService_ClearConversationMessage_Handler,
		},
		{
			MethodName: "UpdateConversationTitle",
			Handler:    _ConversationService_UpdateConversationTitle_Handler,
		},
		{
			MethodName: "UpdateConversationTop",
			Handler:    _ConversationService_UpdateConversationTop_Handler,
		},
		{
			MethodName: "UpdateNotificationStatus",
			Handler:    _ConversationService_UpdateNotificationStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ConversationService.proto",
}
