// Code generated by protoc-gen-go. DO NOT EDIT.
// source: entity.proto

package com_salty_protos

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GrpcReq_Language int32

const (
	GrpcReq_CHINESE GrpcReq_Language = 0
	GrpcReq_ENGLISH GrpcReq_Language = 1
)

var GrpcReq_Language_name = map[int32]string{
	0: "CHINESE",
	1: "ENGLISH",
}

var GrpcReq_Language_value = map[string]int32{
	"CHINESE": 0,
	"ENGLISH": 1,
}

func (x GrpcReq_Language) String() string {
	return proto.EnumName(GrpcReq_Language_name, int32(x))
}

func (GrpcReq_Language) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_cf50d946d740d100, []int{0, 0}
}

type GrpcReq_OS int32

const (
	GrpcReq_UNKNOWN GrpcReq_OS = 0
	GrpcReq_ANDROID GrpcReq_OS = 1
	GrpcReq_IOS     GrpcReq_OS = 2
	GrpcReq_WINDOWS GrpcReq_OS = 3
)

var GrpcReq_OS_name = map[int32]string{
	0: "UNKNOWN",
	1: "ANDROID",
	2: "IOS",
	3: "WINDOWS",
}

var GrpcReq_OS_value = map[string]int32{
	"UNKNOWN": 0,
	"ANDROID": 1,
	"IOS":     2,
	"WINDOWS": 3,
}

func (x GrpcReq_OS) String() string {
	return proto.EnumName(GrpcReq_OS_name, int32(x))
}

func (GrpcReq_OS) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_cf50d946d740d100, []int{0, 1}
}

type UserProfile_Sex int32

const (
	UserProfile_NOT_SET UserProfile_Sex = 0
	UserProfile_MALE    UserProfile_Sex = 1
	UserProfile_FEMALE  UserProfile_Sex = 2
)

var UserProfile_Sex_name = map[int32]string{
	0: "NOT_SET",
	1: "MALE",
	2: "FEMALE",
}

var UserProfile_Sex_value = map[string]int32{
	"NOT_SET": 0,
	"MALE":    1,
	"FEMALE":  2,
}

func (x UserProfile_Sex) String() string {
	return proto.EnumName(UserProfile_Sex_name, int32(x))
}

func (UserProfile_Sex) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_cf50d946d740d100, []int{2, 0}
}

type GroupMemberProfile_GroupRole int32

const (
	GroupMemberProfile_NONE          GroupMemberProfile_GroupRole = 0
	GroupMemberProfile_ADMINISTRATOR GroupMemberProfile_GroupRole = 1
)

var GroupMemberProfile_GroupRole_name = map[int32]string{
	0: "NONE",
	1: "ADMINISTRATOR",
}

var GroupMemberProfile_GroupRole_value = map[string]int32{
	"NONE":          0,
	"ADMINISTRATOR": 1,
}

func (x GroupMemberProfile_GroupRole) String() string {
	return proto.EnumName(GroupMemberProfile_GroupRole_name, int32(x))
}

func (GroupMemberProfile_GroupRole) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_cf50d946d740d100, []int{6, 0}
}

//会话类型
type Conversation_ConversationType int32

const (
	Conversation_NONE    Conversation_ConversationType = 0
	Conversation_PRIVATE Conversation_ConversationType = 1
	Conversation_GROUP   Conversation_ConversationType = 2
)

var Conversation_ConversationType_name = map[int32]string{
	0: "NONE",
	1: "PRIVATE",
	2: "GROUP",
}

var Conversation_ConversationType_value = map[string]int32{
	"NONE":    0,
	"PRIVATE": 1,
	"GROUP":   2,
}

func (x Conversation_ConversationType) String() string {
	return proto.EnumName(Conversation_ConversationType_name, int32(x))
}

func (Conversation_ConversationType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_cf50d946d740d100, []int{7, 0}
}

//会话提醒状态
type Conversation_NotificationStatus int32

const (
	Conversation_NOTIFY         Conversation_NotificationStatus = 0
	Conversation_DO_NOT_DISTURB Conversation_NotificationStatus = 1
)

var Conversation_NotificationStatus_name = map[int32]string{
	0: "NOTIFY",
	1: "DO_NOT_DISTURB",
}

var Conversation_NotificationStatus_value = map[string]int32{
	"NOTIFY":         0,
	"DO_NOT_DISTURB": 1,
}

func (x Conversation_NotificationStatus) String() string {
	return proto.EnumName(Conversation_NotificationStatus_name, int32(x))
}

func (Conversation_NotificationStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_cf50d946d740d100, []int{7, 1}
}

//会话提醒状态
type ChatMessage_SentStatus int32

const (
	ChatMessage_SENDING ChatMessage_SentStatus = 0
	ChatMessage_FAILED  ChatMessage_SentStatus = 1
	ChatMessage_READ    ChatMessage_SentStatus = 2
)

var ChatMessage_SentStatus_name = map[int32]string{
	0: "SENDING",
	1: "FAILED",
	2: "READ",
}

var ChatMessage_SentStatus_value = map[string]int32{
	"SENDING": 0,
	"FAILED":  1,
	"READ":    2,
}

func (x ChatMessage_SentStatus) String() string {
	return proto.EnumName(ChatMessage_SentStatus_name, int32(x))
}

func (ChatMessage_SentStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_cf50d946d740d100, []int{9, 0}
}

//会话提醒状态
type ChatMessage_ReceivedStatus int32

const (
	ChatMessage_RECEIVED   ChatMessage_ReceivedStatus = 0
	ChatMessage_DOWNLOADED ChatMessage_ReceivedStatus = 1
)

var ChatMessage_ReceivedStatus_name = map[int32]string{
	0: "RECEIVED",
	1: "DOWNLOADED",
}

var ChatMessage_ReceivedStatus_value = map[string]int32{
	"RECEIVED":   0,
	"DOWNLOADED": 1,
}

func (x ChatMessage_ReceivedStatus) String() string {
	return proto.EnumName(ChatMessage_ReceivedStatus_name, int32(x))
}

func (ChatMessage_ReceivedStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_cf50d946d740d100, []int{9, 1}
}

//消息的发送方向
type ChatMessage_MessageDirection int32

const (
	ChatMessage_SEND    ChatMessage_MessageDirection = 0
	ChatMessage_RECEIVE ChatMessage_MessageDirection = 1
)

var ChatMessage_MessageDirection_name = map[int32]string{
	0: "SEND",
	1: "RECEIVE",
}

var ChatMessage_MessageDirection_value = map[string]int32{
	"SEND":    0,
	"RECEIVE": 1,
}

func (x ChatMessage_MessageDirection) String() string {
	return proto.EnumName(ChatMessage_MessageDirection_name, int32(x))
}

func (ChatMessage_MessageDirection) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_cf50d946d740d100, []int{9, 2}
}

//操作类型
type ContactOperationMessage_OperationType int32

const (
	ContactOperationMessage_REQUEST ContactOperationMessage_OperationType = 0
	ContactOperationMessage_ACCEPT  ContactOperationMessage_OperationType = 1
	ContactOperationMessage_REJECT  ContactOperationMessage_OperationType = 2
	ContactOperationMessage_DELETE  ContactOperationMessage_OperationType = 3
)

var ContactOperationMessage_OperationType_name = map[int32]string{
	0: "REQUEST",
	1: "ACCEPT",
	2: "REJECT",
	3: "DELETE",
}

var ContactOperationMessage_OperationType_value = map[string]int32{
	"REQUEST": 0,
	"ACCEPT":  1,
	"REJECT":  2,
	"DELETE":  3,
}

func (x ContactOperationMessage_OperationType) String() string {
	return proto.EnumName(ContactOperationMessage_OperationType_name, int32(x))
}

func (ContactOperationMessage_OperationType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_cf50d946d740d100, []int{10, 0}
}

// Basic Request
type GrpcReq struct {
	DeviceId             string           `protobuf:"bytes,1,opt,name=deviceId,proto3" json:"deviceId,omitempty"`
	Version              string           `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Language             GrpcReq_Language `protobuf:"varint,3,opt,name=language,proto3,enum=com.salty.protos.GrpcReq_Language" json:"language,omitempty"`
	Os                   GrpcReq_OS       `protobuf:"varint,4,opt,name=os,proto3,enum=com.salty.protos.GrpcReq_OS" json:"os,omitempty"`
	Token                string           `protobuf:"bytes,5,opt,name=token,proto3" json:"token,omitempty"`
	Data                 *any.Any         `protobuf:"bytes,6,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *GrpcReq) Reset()         { *m = GrpcReq{} }
func (m *GrpcReq) String() string { return proto.CompactTextString(m) }
func (*GrpcReq) ProtoMessage()    {}
func (*GrpcReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf50d946d740d100, []int{0}
}

func (m *GrpcReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GrpcReq.Unmarshal(m, b)
}
func (m *GrpcReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GrpcReq.Marshal(b, m, deterministic)
}
func (m *GrpcReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GrpcReq.Merge(m, src)
}
func (m *GrpcReq) XXX_Size() int {
	return xxx_messageInfo_GrpcReq.Size(m)
}
func (m *GrpcReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GrpcReq.DiscardUnknown(m)
}

var xxx_messageInfo_GrpcReq proto.InternalMessageInfo

func (m *GrpcReq) GetDeviceId() string {
	if m != nil {
		return m.DeviceId
	}
	return ""
}

func (m *GrpcReq) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *GrpcReq) GetLanguage() GrpcReq_Language {
	if m != nil {
		return m.Language
	}
	return GrpcReq_CHINESE
}

func (m *GrpcReq) GetOs() GrpcReq_OS {
	if m != nil {
		return m.Os
	}
	return GrpcReq_UNKNOWN
}

func (m *GrpcReq) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *GrpcReq) GetData() *any.Any {
	if m != nil {
		return m.Data
	}
	return nil
}

// Basic Response
type GrpcResp struct {
	Code                 StatusCode `protobuf:"varint,1,opt,name=code,proto3,enum=com.salty.protos.StatusCode" json:"code,omitempty"`
	Message              string     `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data                 *any.Any   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GrpcResp) Reset()         { *m = GrpcResp{} }
func (m *GrpcResp) String() string { return proto.CompactTextString(m) }
func (*GrpcResp) ProtoMessage()    {}
func (*GrpcResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf50d946d740d100, []int{1}
}

func (m *GrpcResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GrpcResp.Unmarshal(m, b)
}
func (m *GrpcResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GrpcResp.Marshal(b, m, deterministic)
}
func (m *GrpcResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GrpcResp.Merge(m, src)
}
func (m *GrpcResp) XXX_Size() int {
	return xxx_messageInfo_GrpcResp.Size(m)
}
func (m *GrpcResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GrpcResp.DiscardUnknown(m)
}

var xxx_messageInfo_GrpcResp proto.InternalMessageInfo

func (m *GrpcResp) GetCode() StatusCode {
	if m != nil {
		return m.Code
	}
	return StatusCode_STATUS_UNKNOWN
}

func (m *GrpcResp) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *GrpcResp) GetData() *any.Any {
	if m != nil {
		return m.Data
	}
	return nil
}

type UserProfile struct {
	UserId               string          `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Telephone            string          `protobuf:"bytes,2,opt,name=telephone,proto3" json:"telephone,omitempty"`
	Email                string          `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Nickname             string          `protobuf:"bytes,4,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Avatar               string          `protobuf:"bytes,5,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Description          string          `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	Sex                  UserProfile_Sex `protobuf:"varint,7,opt,name=sex,proto3,enum=com.salty.protos.UserProfile_Sex" json:"sex,omitempty"`
	Birthday             int64           `protobuf:"varint,8,opt,name=birthday,proto3" json:"birthday,omitempty"`
	Location             string          `protobuf:"bytes,9,opt,name=location,proto3" json:"location,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *UserProfile) Reset()         { *m = UserProfile{} }
func (m *UserProfile) String() string { return proto.CompactTextString(m) }
func (*UserProfile) ProtoMessage()    {}
func (*UserProfile) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf50d946d740d100, []int{2}
}

func (m *UserProfile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserProfile.Unmarshal(m, b)
}
func (m *UserProfile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserProfile.Marshal(b, m, deterministic)
}
func (m *UserProfile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserProfile.Merge(m, src)
}
func (m *UserProfile) XXX_Size() int {
	return xxx_messageInfo_UserProfile.Size(m)
}
func (m *UserProfile) XXX_DiscardUnknown() {
	xxx_messageInfo_UserProfile.DiscardUnknown(m)
}

var xxx_messageInfo_UserProfile proto.InternalMessageInfo

func (m *UserProfile) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *UserProfile) GetTelephone() string {
	if m != nil {
		return m.Telephone
	}
	return ""
}

func (m *UserProfile) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UserProfile) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *UserProfile) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *UserProfile) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *UserProfile) GetSex() UserProfile_Sex {
	if m != nil {
		return m.Sex
	}
	return UserProfile_NOT_SET
}

func (m *UserProfile) GetBirthday() int64 {
	if m != nil {
		return m.Birthday
	}
	return 0
}

func (m *UserProfile) GetLocation() string {
	if m != nil {
		return m.Location
	}
	return ""
}

type ContactProfile struct {
	UserProfile          *UserProfile   `protobuf:"bytes,1,opt,name=userProfile,proto3" json:"userProfile,omitempty"`
	RemarkInfo           *ContactRemark `protobuf:"bytes,2,opt,name=remarkInfo,proto3" json:"remarkInfo,omitempty"`
	SortId               string         `protobuf:"bytes,3,opt,name=sortId,proto3" json:"sortId,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ContactProfile) Reset()         { *m = ContactProfile{} }
func (m *ContactProfile) String() string { return proto.CompactTextString(m) }
func (*ContactProfile) ProtoMessage()    {}
func (*ContactProfile) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf50d946d740d100, []int{3}
}

func (m *ContactProfile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContactProfile.Unmarshal(m, b)
}
func (m *ContactProfile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContactProfile.Marshal(b, m, deterministic)
}
func (m *ContactProfile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContactProfile.Merge(m, src)
}
func (m *ContactProfile) XXX_Size() int {
	return xxx_messageInfo_ContactProfile.Size(m)
}
func (m *ContactProfile) XXX_DiscardUnknown() {
	xxx_messageInfo_ContactProfile.DiscardUnknown(m)
}

var xxx_messageInfo_ContactProfile proto.InternalMessageInfo

func (m *ContactProfile) GetUserProfile() *UserProfile {
	if m != nil {
		return m.UserProfile
	}
	return nil
}

func (m *ContactProfile) GetRemarkInfo() *ContactRemark {
	if m != nil {
		return m.RemarkInfo
	}
	return nil
}

func (m *ContactProfile) GetSortId() string {
	if m != nil {
		return m.SortId
	}
	return ""
}

type ContactRemark struct {
	RemarkName           string   `protobuf:"bytes,1,opt,name=remarkName,proto3" json:"remarkName,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Telephones           []string `protobuf:"bytes,3,rep,name=telephones,proto3" json:"telephones,omitempty"`
	Tags                 []string `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ContactRemark) Reset()         { *m = ContactRemark{} }
func (m *ContactRemark) String() string { return proto.CompactTextString(m) }
func (*ContactRemark) ProtoMessage()    {}
func (*ContactRemark) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf50d946d740d100, []int{4}
}

func (m *ContactRemark) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContactRemark.Unmarshal(m, b)
}
func (m *ContactRemark) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContactRemark.Marshal(b, m, deterministic)
}
func (m *ContactRemark) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContactRemark.Merge(m, src)
}
func (m *ContactRemark) XXX_Size() int {
	return xxx_messageInfo_ContactRemark.Size(m)
}
func (m *ContactRemark) XXX_DiscardUnknown() {
	xxx_messageInfo_ContactRemark.DiscardUnknown(m)
}

var xxx_messageInfo_ContactRemark proto.InternalMessageInfo

func (m *ContactRemark) GetRemarkName() string {
	if m != nil {
		return m.RemarkName
	}
	return ""
}

func (m *ContactRemark) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *ContactRemark) GetTelephones() []string {
	if m != nil {
		return m.Telephones
	}
	return nil
}

func (m *ContactRemark) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

type GroupProfile struct {
	GroupId              string                `protobuf:"bytes,1,opt,name=groupId,proto3" json:"groupId,omitempty"`
	Name                 string                `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CreateTime           int64                 `protobuf:"varint,3,opt,name=createTime,proto3" json:"createTime,omitempty"`
	OwnerUserId          string                `protobuf:"bytes,4,opt,name=ownerUserId,proto3" json:"ownerUserId,omitempty"`
	Avatar               string                `protobuf:"bytes,5,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Notice               string                `protobuf:"bytes,6,opt,name=notice,proto3" json:"notice,omitempty"`
	Members              []*GroupMemberProfile `protobuf:"bytes,7,rep,name=members,proto3" json:"members,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *GroupProfile) Reset()         { *m = GroupProfile{} }
func (m *GroupProfile) String() string { return proto.CompactTextString(m) }
func (*GroupProfile) ProtoMessage()    {}
func (*GroupProfile) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf50d946d740d100, []int{5}
}

func (m *GroupProfile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GroupProfile.Unmarshal(m, b)
}
func (m *GroupProfile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GroupProfile.Marshal(b, m, deterministic)
}
func (m *GroupProfile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GroupProfile.Merge(m, src)
}
func (m *GroupProfile) XXX_Size() int {
	return xxx_messageInfo_GroupProfile.Size(m)
}
func (m *GroupProfile) XXX_DiscardUnknown() {
	xxx_messageInfo_GroupProfile.DiscardUnknown(m)
}

var xxx_messageInfo_GroupProfile proto.InternalMessageInfo

func (m *GroupProfile) GetGroupId() string {
	if m != nil {
		return m.GroupId
	}
	return ""
}

func (m *GroupProfile) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GroupProfile) GetCreateTime() int64 {
	if m != nil {
		return m.CreateTime
	}
	return 0
}

func (m *GroupProfile) GetOwnerUserId() string {
	if m != nil {
		return m.OwnerUserId
	}
	return ""
}

func (m *GroupProfile) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *GroupProfile) GetNotice() string {
	if m != nil {
		return m.Notice
	}
	return ""
}

func (m *GroupProfile) GetMembers() []*GroupMemberProfile {
	if m != nil {
		return m.Members
	}
	return nil
}

type GroupMemberProfile struct {
	GroupId              string                       `protobuf:"bytes,1,opt,name=groupId,proto3" json:"groupId,omitempty"`
	Alias                string                       `protobuf:"bytes,2,opt,name=alias,proto3" json:"alias,omitempty"`
	Role                 GroupMemberProfile_GroupRole `protobuf:"varint,3,opt,name=role,proto3,enum=com.salty.protos.GroupMemberProfile_GroupRole" json:"role,omitempty"`
	JoinTime             int64                        `protobuf:"varint,4,opt,name=joinTime,proto3" json:"joinTime,omitempty"`
	UserProfile          *UserProfile                 `protobuf:"bytes,5,opt,name=userProfile,proto3" json:"userProfile,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *GroupMemberProfile) Reset()         { *m = GroupMemberProfile{} }
func (m *GroupMemberProfile) String() string { return proto.CompactTextString(m) }
func (*GroupMemberProfile) ProtoMessage()    {}
func (*GroupMemberProfile) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf50d946d740d100, []int{6}
}

func (m *GroupMemberProfile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GroupMemberProfile.Unmarshal(m, b)
}
func (m *GroupMemberProfile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GroupMemberProfile.Marshal(b, m, deterministic)
}
func (m *GroupMemberProfile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GroupMemberProfile.Merge(m, src)
}
func (m *GroupMemberProfile) XXX_Size() int {
	return xxx_messageInfo_GroupMemberProfile.Size(m)
}
func (m *GroupMemberProfile) XXX_DiscardUnknown() {
	xxx_messageInfo_GroupMemberProfile.DiscardUnknown(m)
}

var xxx_messageInfo_GroupMemberProfile proto.InternalMessageInfo

func (m *GroupMemberProfile) GetGroupId() string {
	if m != nil {
		return m.GroupId
	}
	return ""
}

func (m *GroupMemberProfile) GetAlias() string {
	if m != nil {
		return m.Alias
	}
	return ""
}

func (m *GroupMemberProfile) GetRole() GroupMemberProfile_GroupRole {
	if m != nil {
		return m.Role
	}
	return GroupMemberProfile_NONE
}

func (m *GroupMemberProfile) GetJoinTime() int64 {
	if m != nil {
		return m.JoinTime
	}
	return 0
}

func (m *GroupMemberProfile) GetUserProfile() *UserProfile {
	if m != nil {
		return m.UserProfile
	}
	return nil
}

type Conversation struct {
	ConversationId       string                          `protobuf:"bytes,1,opt,name=conversationId,proto3" json:"conversationId,omitempty"`
	ConversationTitle    string                          `protobuf:"bytes,2,opt,name=conversationTitle,proto3" json:"conversationTitle,omitempty"`
	PortraitUrl          string                          `protobuf:"bytes,3,opt,name=portraitUrl,proto3" json:"portraitUrl,omitempty"`
	UnreadMessageCount   int32                           `protobuf:"varint,4,opt,name=unreadMessageCount,proto3" json:"unreadMessageCount,omitempty"`
	IsTop                bool                            `protobuf:"varint,5,opt,name=isTop,proto3" json:"isTop,omitempty"`
	LatestMessage        *ChatMessage                    `protobuf:"bytes,6,opt,name=latestMessage,proto3" json:"latestMessage,omitempty"`
	Draft                string                          `protobuf:"bytes,7,opt,name=draft,proto3" json:"draft,omitempty"`
	ConversationType     Conversation_ConversationType   `protobuf:"varint,8,opt,name=conversationType,proto3,enum=com.salty.protos.Conversation_ConversationType" json:"conversationType,omitempty"`
	NotificationStatus   Conversation_NotificationStatus `protobuf:"varint,9,opt,name=notificationStatus,proto3,enum=com.salty.protos.Conversation_NotificationStatus" json:"notificationStatus,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                        `json:"-"`
	XXX_unrecognized     []byte                          `json:"-"`
	XXX_sizecache        int32                           `json:"-"`
}

func (m *Conversation) Reset()         { *m = Conversation{} }
func (m *Conversation) String() string { return proto.CompactTextString(m) }
func (*Conversation) ProtoMessage()    {}
func (*Conversation) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf50d946d740d100, []int{7}
}

func (m *Conversation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Conversation.Unmarshal(m, b)
}
func (m *Conversation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Conversation.Marshal(b, m, deterministic)
}
func (m *Conversation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Conversation.Merge(m, src)
}
func (m *Conversation) XXX_Size() int {
	return xxx_messageInfo_Conversation.Size(m)
}
func (m *Conversation) XXX_DiscardUnknown() {
	xxx_messageInfo_Conversation.DiscardUnknown(m)
}

var xxx_messageInfo_Conversation proto.InternalMessageInfo

func (m *Conversation) GetConversationId() string {
	if m != nil {
		return m.ConversationId
	}
	return ""
}

func (m *Conversation) GetConversationTitle() string {
	if m != nil {
		return m.ConversationTitle
	}
	return ""
}

func (m *Conversation) GetPortraitUrl() string {
	if m != nil {
		return m.PortraitUrl
	}
	return ""
}

func (m *Conversation) GetUnreadMessageCount() int32 {
	if m != nil {
		return m.UnreadMessageCount
	}
	return 0
}

func (m *Conversation) GetIsTop() bool {
	if m != nil {
		return m.IsTop
	}
	return false
}

func (m *Conversation) GetLatestMessage() *ChatMessage {
	if m != nil {
		return m.LatestMessage
	}
	return nil
}

func (m *Conversation) GetDraft() string {
	if m != nil {
		return m.Draft
	}
	return ""
}

func (m *Conversation) GetConversationType() Conversation_ConversationType {
	if m != nil {
		return m.ConversationType
	}
	return Conversation_NONE
}

func (m *Conversation) GetNotificationStatus() Conversation_NotificationStatus {
	if m != nil {
		return m.NotificationStatus
	}
	return Conversation_NOTIFY
}

type MessageCommon struct {
	MessageId            string   `protobuf:"bytes,1,opt,name=messageId,proto3" json:"messageId,omitempty"`
	CreatedTime          int64    `protobuf:"varint,2,opt,name=createdTime,proto3" json:"createdTime,omitempty"`
	IsNeedRemind         bool     `protobuf:"varint,3,opt,name=isNeedRemind,proto3" json:"isNeedRemind,omitempty"`
	SortId               string   `protobuf:"bytes,4,opt,name=sortId,proto3" json:"sortId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageCommon) Reset()         { *m = MessageCommon{} }
func (m *MessageCommon) String() string { return proto.CompactTextString(m) }
func (*MessageCommon) ProtoMessage()    {}
func (*MessageCommon) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf50d946d740d100, []int{8}
}

func (m *MessageCommon) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageCommon.Unmarshal(m, b)
}
func (m *MessageCommon) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageCommon.Marshal(b, m, deterministic)
}
func (m *MessageCommon) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageCommon.Merge(m, src)
}
func (m *MessageCommon) XXX_Size() int {
	return xxx_messageInfo_MessageCommon.Size(m)
}
func (m *MessageCommon) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageCommon.DiscardUnknown(m)
}

var xxx_messageInfo_MessageCommon proto.InternalMessageInfo

func (m *MessageCommon) GetMessageId() string {
	if m != nil {
		return m.MessageId
	}
	return ""
}

func (m *MessageCommon) GetCreatedTime() int64 {
	if m != nil {
		return m.CreatedTime
	}
	return 0
}

func (m *MessageCommon) GetIsNeedRemind() bool {
	if m != nil {
		return m.IsNeedRemind
	}
	return false
}

func (m *MessageCommon) GetSortId() string {
	if m != nil {
		return m.SortId
	}
	return ""
}

type ChatMessage struct {
	Common               *MessageCommon             `protobuf:"bytes,1,opt,name=common,proto3" json:"common,omitempty"`
	TargetId             string                     `protobuf:"bytes,2,opt,name=targetId,proto3" json:"targetId,omitempty"`
	ReadTime             int64                      `protobuf:"varint,3,opt,name=readTime,proto3" json:"readTime,omitempty"`
	SentStatus           ChatMessage_SentStatus     `protobuf:"varint,4,opt,name=sentStatus,proto3,enum=com.salty.protos.ChatMessage_SentStatus" json:"sentStatus,omitempty"`
	ReceivedStatus       ChatMessage_ReceivedStatus `protobuf:"varint,5,opt,name=receivedStatus,proto3,enum=com.salty.protos.ChatMessage_ReceivedStatus" json:"receivedStatus,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *ChatMessage) Reset()         { *m = ChatMessage{} }
func (m *ChatMessage) String() string { return proto.CompactTextString(m) }
func (*ChatMessage) ProtoMessage()    {}
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf50d946d740d100, []int{9}
}

func (m *ChatMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChatMessage.Unmarshal(m, b)
}
func (m *ChatMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChatMessage.Marshal(b, m, deterministic)
}
func (m *ChatMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChatMessage.Merge(m, src)
}
func (m *ChatMessage) XXX_Size() int {
	return xxx_messageInfo_ChatMessage.Size(m)
}
func (m *ChatMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ChatMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ChatMessage proto.InternalMessageInfo

func (m *ChatMessage) GetCommon() *MessageCommon {
	if m != nil {
		return m.Common
	}
	return nil
}

func (m *ChatMessage) GetTargetId() string {
	if m != nil {
		return m.TargetId
	}
	return ""
}

func (m *ChatMessage) GetReadTime() int64 {
	if m != nil {
		return m.ReadTime
	}
	return 0
}

func (m *ChatMessage) GetSentStatus() ChatMessage_SentStatus {
	if m != nil {
		return m.SentStatus
	}
	return ChatMessage_SENDING
}

func (m *ChatMessage) GetReceivedStatus() ChatMessage_ReceivedStatus {
	if m != nil {
		return m.ReceivedStatus
	}
	return ChatMessage_RECEIVED
}

type ContactOperationMessage struct {
	Common               *MessageCommon                        `protobuf:"bytes,1,opt,name=common,proto3" json:"common,omitempty"`
	TriggerProfile       *UserProfile                          `protobuf:"bytes,2,opt,name=triggerProfile,proto3" json:"triggerProfile,omitempty"`
	AddReason            string                                `protobuf:"bytes,3,opt,name=addReason,proto3" json:"addReason,omitempty"`
	RejectReason         string                                `protobuf:"bytes,4,opt,name=rejectReason,proto3" json:"rejectReason,omitempty"`
	Type                 ContactOperationMessage_OperationType `protobuf:"varint,5,opt,name=type,proto3,enum=com.salty.protos.ContactOperationMessage_OperationType" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                              `json:"-"`
	XXX_unrecognized     []byte                                `json:"-"`
	XXX_sizecache        int32                                 `json:"-"`
}

func (m *ContactOperationMessage) Reset()         { *m = ContactOperationMessage{} }
func (m *ContactOperationMessage) String() string { return proto.CompactTextString(m) }
func (*ContactOperationMessage) ProtoMessage()    {}
func (*ContactOperationMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf50d946d740d100, []int{10}
}

func (m *ContactOperationMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContactOperationMessage.Unmarshal(m, b)
}
func (m *ContactOperationMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContactOperationMessage.Marshal(b, m, deterministic)
}
func (m *ContactOperationMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContactOperationMessage.Merge(m, src)
}
func (m *ContactOperationMessage) XXX_Size() int {
	return xxx_messageInfo_ContactOperationMessage.Size(m)
}
func (m *ContactOperationMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ContactOperationMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ContactOperationMessage proto.InternalMessageInfo

func (m *ContactOperationMessage) GetCommon() *MessageCommon {
	if m != nil {
		return m.Common
	}
	return nil
}

func (m *ContactOperationMessage) GetTriggerProfile() *UserProfile {
	if m != nil {
		return m.TriggerProfile
	}
	return nil
}

func (m *ContactOperationMessage) GetAddReason() string {
	if m != nil {
		return m.AddReason
	}
	return ""
}

func (m *ContactOperationMessage) GetRejectReason() string {
	if m != nil {
		return m.RejectReason
	}
	return ""
}

func (m *ContactOperationMessage) GetType() ContactOperationMessage_OperationType {
	if m != nil {
		return m.Type
	}
	return ContactOperationMessage_REQUEST
}

type EmptyResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmptyResp) Reset()         { *m = EmptyResp{} }
func (m *EmptyResp) String() string { return proto.CompactTextString(m) }
func (*EmptyResp) ProtoMessage()    {}
func (*EmptyResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf50d946d740d100, []int{11}
}

func (m *EmptyResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmptyResp.Unmarshal(m, b)
}
func (m *EmptyResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmptyResp.Marshal(b, m, deterministic)
}
func (m *EmptyResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmptyResp.Merge(m, src)
}
func (m *EmptyResp) XXX_Size() int {
	return xxx_messageInfo_EmptyResp.Size(m)
}
func (m *EmptyResp) XXX_DiscardUnknown() {
	xxx_messageInfo_EmptyResp.DiscardUnknown(m)
}

var xxx_messageInfo_EmptyResp proto.InternalMessageInfo

func init() {
	proto.RegisterEnum("com.salty.protos.GrpcReq_Language", GrpcReq_Language_name, GrpcReq_Language_value)
	proto.RegisterEnum("com.salty.protos.GrpcReq_OS", GrpcReq_OS_name, GrpcReq_OS_value)
	proto.RegisterEnum("com.salty.protos.UserProfile_Sex", UserProfile_Sex_name, UserProfile_Sex_value)
	proto.RegisterEnum("com.salty.protos.GroupMemberProfile_GroupRole", GroupMemberProfile_GroupRole_name, GroupMemberProfile_GroupRole_value)
	proto.RegisterEnum("com.salty.protos.Conversation_ConversationType", Conversation_ConversationType_name, Conversation_ConversationType_value)
	proto.RegisterEnum("com.salty.protos.Conversation_NotificationStatus", Conversation_NotificationStatus_name, Conversation_NotificationStatus_value)
	proto.RegisterEnum("com.salty.protos.ChatMessage_SentStatus", ChatMessage_SentStatus_name, ChatMessage_SentStatus_value)
	proto.RegisterEnum("com.salty.protos.ChatMessage_ReceivedStatus", ChatMessage_ReceivedStatus_name, ChatMessage_ReceivedStatus_value)
	proto.RegisterEnum("com.salty.protos.ChatMessage_MessageDirection", ChatMessage_MessageDirection_name, ChatMessage_MessageDirection_value)
	proto.RegisterEnum("com.salty.protos.ContactOperationMessage_OperationType", ContactOperationMessage_OperationType_name, ContactOperationMessage_OperationType_value)
	proto.RegisterType((*GrpcReq)(nil), "com.salty.protos.GrpcReq")
	proto.RegisterType((*GrpcResp)(nil), "com.salty.protos.GrpcResp")
	proto.RegisterType((*UserProfile)(nil), "com.salty.protos.UserProfile")
	proto.RegisterType((*ContactProfile)(nil), "com.salty.protos.ContactProfile")
	proto.RegisterType((*ContactRemark)(nil), "com.salty.protos.ContactRemark")
	proto.RegisterType((*GroupProfile)(nil), "com.salty.protos.GroupProfile")
	proto.RegisterType((*GroupMemberProfile)(nil), "com.salty.protos.GroupMemberProfile")
	proto.RegisterType((*Conversation)(nil), "com.salty.protos.Conversation")
	proto.RegisterType((*MessageCommon)(nil), "com.salty.protos.MessageCommon")
	proto.RegisterType((*ChatMessage)(nil), "com.salty.protos.ChatMessage")
	proto.RegisterType((*ContactOperationMessage)(nil), "com.salty.protos.ContactOperationMessage")
	proto.RegisterType((*EmptyResp)(nil), "com.salty.protos.EmptyResp")
}

func init() { proto.RegisterFile("entity.proto", fileDescriptor_cf50d946d740d100) }

var fileDescriptor_cf50d946d740d100 = []byte{
	// 1362 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x56, 0xcd, 0x6e, 0xdb, 0xc6,
	0x16, 0x36, 0x29, 0xd9, 0x92, 0x8e, 0x6c, 0x81, 0x19, 0x04, 0xb9, 0xba, 0x41, 0x6e, 0xae, 0x4b,
	0x04, 0x85, 0x0a, 0x04, 0x72, 0xeb, 0x04, 0xc8, 0x2e, 0xa9, 0x22, 0x31, 0x0e, 0x1b, 0x9b, 0x74,
	0x87, 0x74, 0x8c, 0xa2, 0x8b, 0x60, 0x4c, 0x8e, 0x15, 0x26, 0x12, 0x47, 0x1d, 0x8e, 0xdc, 0x78,
	0xd7, 0x4d, 0x57, 0x5d, 0xf4, 0x3d, 0xf2, 0x20, 0x05, 0xba, 0xee, 0x5b, 0x74, 0xd1, 0x67, 0x28,
	0x66, 0x86, 0xa4, 0x28, 0xc9, 0x71, 0x52, 0x74, 0xc7, 0xef, 0xcc, 0x9c, 0x9f, 0x39, 0xe7, 0x9b,
	0x6f, 0x08, 0xdb, 0x34, 0x15, 0x89, 0xb8, 0xec, 0xcf, 0x38, 0x13, 0x0c, 0x59, 0x11, 0x9b, 0xf6,
	0x33, 0x32, 0x29, 0x0c, 0xd9, 0xed, 0xff, 0x8e, 0x19, 0x1b, 0x4f, 0xe8, 0x9e, 0x82, 0x67, 0xf3,
	0xf3, 0x3d, 0x92, 0xe6, 0x6b, 0xb7, 0xad, 0x40, 0x10, 0x31, 0xcf, 0x86, 0x2c, 0xa6, 0xda, 0x62,
	0xff, 0x6e, 0x42, 0xe3, 0x80, 0xcf, 0x22, 0x4c, 0x7f, 0x40, 0xb7, 0xa1, 0x19, 0xd3, 0x8b, 0x24,
	0xa2, 0x6e, 0xdc, 0x35, 0x76, 0x8d, 0x5e, 0x0b, 0x97, 0x18, 0x75, 0xa1, 0x71, 0x41, 0x79, 0x96,
	0xb0, 0xb4, 0x6b, 0xaa, 0xa5, 0x02, 0xa2, 0xc7, 0xd0, 0x9c, 0x90, 0x74, 0x3c, 0x27, 0x63, 0xda,
	0xad, 0xed, 0x1a, 0xbd, 0xce, 0xbe, 0xdd, 0x5f, 0xad, 0xa9, 0x9f, 0xa7, 0xe8, 0x1f, 0xe6, 0x3b,
	0x71, 0xe9, 0x83, 0xee, 0x83, 0xc9, 0xb2, 0x6e, 0x5d, 0x79, 0xde, 0xf9, 0xb0, 0xa7, 0x1f, 0x60,
	0x93, 0x65, 0xe8, 0x26, 0x6c, 0x0a, 0xf6, 0x96, 0xa6, 0xdd, 0x4d, 0x55, 0x85, 0x06, 0xa8, 0x07,
	0xf5, 0x98, 0x08, 0xd2, 0xdd, 0xda, 0x35, 0x7a, 0xed, 0xfd, 0x9b, 0x7d, 0xdd, 0x81, 0x7e, 0xd1,
	0x81, 0xfe, 0x20, 0xbd, 0xc4, 0x6a, 0x87, 0x7d, 0x0f, 0x9a, 0x45, 0x0d, 0xa8, 0x0d, 0x8d, 0xe1,
	0x73, 0xd7, 0x73, 0x02, 0xc7, 0xda, 0x90, 0xc0, 0xf1, 0x0e, 0x0e, 0xdd, 0xe0, 0xb9, 0x65, 0xd8,
	0x0f, 0xc1, 0xf4, 0x03, 0x69, 0x3a, 0xf1, 0x5e, 0x78, 0xfe, 0xa9, 0xa7, 0xd7, 0x07, 0xde, 0x08,
	0xfb, 0xee, 0xc8, 0x32, 0x50, 0x03, 0x6a, 0xae, 0x1f, 0x58, 0xa6, 0xb4, 0x9e, 0xba, 0xde, 0xc8,
	0x3f, 0x0d, 0xac, 0x9a, 0xfd, 0x93, 0x01, 0x4d, 0x5d, 0x6e, 0x36, 0x43, 0x5f, 0x42, 0x3d, 0x62,
	0x31, 0x55, 0x8d, 0xbc, 0xf2, 0x60, 0x8b, 0x51, 0x60, 0xb5, 0x53, 0xb6, 0x78, 0x4a, 0xb3, 0x4c,
	0xf6, 0x31, 0x6f, 0x71, 0x0e, 0xcb, 0xe3, 0xd5, 0x3e, 0x7a, 0xbc, 0xdf, 0x4c, 0x68, 0x9f, 0x64,
	0x94, 0x1f, 0x73, 0x76, 0x9e, 0x4c, 0x28, 0xba, 0x05, 0x5b, 0xf3, 0x8c, 0xf2, 0x72, 0xa0, 0x39,
	0x42, 0x77, 0xa0, 0x25, 0xe8, 0x84, 0xce, 0x5e, 0xb3, 0xb4, 0xc8, 0xb6, 0x30, 0xc8, 0x26, 0xd3,
	0x29, 0x49, 0x26, 0x2a, 0x61, 0x0b, 0x6b, 0x20, 0xe9, 0x91, 0x26, 0xd1, 0xdb, 0x94, 0x4c, 0xa9,
	0x1a, 0x57, 0x0b, 0x97, 0x58, 0xe6, 0x21, 0x17, 0x44, 0x10, 0x9e, 0xcf, 0x25, 0x47, 0x68, 0x17,
	0xda, 0x31, 0xcd, 0x22, 0x9e, 0xcc, 0x84, 0xa4, 0xce, 0x96, 0x5a, 0xac, 0x9a, 0xd0, 0x03, 0xa8,
	0x65, 0xf4, 0x5d, 0xb7, 0xa1, 0xda, 0xf4, 0xd9, 0x7a, 0x9b, 0x2a, 0xa7, 0xe9, 0x07, 0xf4, 0x1d,
	0x96, 0xbb, 0x65, 0x29, 0x67, 0x09, 0x17, 0xaf, 0x63, 0x72, 0xd9, 0x6d, 0xee, 0x1a, 0xbd, 0x1a,
	0x2e, 0xb1, 0x5c, 0x9b, 0xb0, 0x88, 0xa8, 0x7c, 0x2d, 0x5d, 0x66, 0x81, 0xed, 0x1e, 0xd4, 0x02,
	0xfa, 0x4e, 0x4e, 0xcd, 0xf3, 0xc3, 0x57, 0x81, 0x13, 0x5a, 0x1b, 0xa8, 0x09, 0xf5, 0xa3, 0xc1,
	0xa1, 0x63, 0x19, 0x08, 0x60, 0xeb, 0x99, 0xa3, 0xbe, 0x4d, 0xfb, 0xbd, 0x01, 0x9d, 0x21, 0x4b,
	0x05, 0x89, 0x44, 0xd1, 0xcb, 0x27, 0xd0, 0x9e, 0x2f, 0x8a, 0x51, 0x0d, 0x6d, 0xef, 0xff, 0xef,
	0xda, 0x8a, 0x71, 0xd5, 0x03, 0x3d, 0x01, 0xe0, 0x74, 0x4a, 0xf8, 0x5b, 0x37, 0x3d, 0x67, 0xaa,
	0xeb, 0xed, 0xfd, 0xff, 0xaf, 0xfb, 0xe7, 0x69, 0xb1, 0xda, 0x8a, 0x2b, 0x2e, 0xb2, 0xcb, 0x19,
	0xe3, 0xc2, 0x8d, 0xf3, 0xc1, 0xe4, 0xc8, 0xfe, 0xd9, 0x80, 0x9d, 0x25, 0x2f, 0x74, 0xb7, 0x48,
	0xe5, 0xc9, 0x69, 0xe9, 0xd9, 0x57, 0x2c, 0xab, 0x73, 0x31, 0xd7, 0xe7, 0x72, 0x17, 0xa0, 0x24,
	0x44, 0xd6, 0xad, 0xed, 0xd6, 0x64, 0x84, 0x85, 0x05, 0x21, 0xa8, 0x0b, 0x32, 0x96, 0x17, 0x57,
	0xae, 0xa8, 0x6f, 0xfb, 0x2f, 0x03, 0xb6, 0x0f, 0x38, 0x9b, 0xcf, 0x8a, 0x13, 0x77, 0xa1, 0x31,
	0x96, 0xb8, 0xe4, 0x5f, 0x01, 0xa5, 0xbb, 0x22, 0x92, 0xce, 0xac, 0xbe, 0x65, 0xca, 0x88, 0x53,
	0x22, 0x68, 0x98, 0x4c, 0xb5, 0x96, 0xd4, 0x70, 0xc5, 0x22, 0x8b, 0x66, 0x3f, 0xa6, 0x94, 0x9f,
	0x68, 0x46, 0x6b, 0x0e, 0x56, 0x4d, 0x1f, 0xa4, 0xe1, 0x2d, 0xd8, 0x4a, 0x99, 0x48, 0x22, 0x9a,
	0x33, 0x30, 0x47, 0xe8, 0xb1, 0xbc, 0x72, 0xd3, 0x33, 0xca, 0xb3, 0x6e, 0x63, 0xb7, 0xd6, 0x6b,
	0xef, 0xdf, 0xbb, 0x4a, 0x80, 0xd8, 0x7c, 0x76, 0xa4, 0x76, 0x15, 0x53, 0x2d, 0x9c, 0xec, 0x5f,
	0x4d, 0x40, 0xeb, 0xeb, 0xd7, 0x1c, 0xfb, 0x26, 0x6c, 0x92, 0x49, 0x42, 0xb2, 0xfc, 0xdc, 0x1a,
	0xa0, 0xa7, 0x50, 0xe7, 0x6c, 0x52, 0xc8, 0x67, 0xff, 0x53, 0x6a, 0xd0, 0x26, 0xcc, 0x26, 0x14,
	0x2b, 0x5f, 0x49, 0xfb, 0x37, 0x2c, 0x49, 0x55, 0xeb, 0xea, 0xfa, 0x4a, 0x14, 0x78, 0x95, 0xb9,
	0x9b, 0xff, 0x94, 0xb9, 0x76, 0x0f, 0x5a, 0x65, 0x3e, 0x79, 0x61, 0x3c, 0xdf, 0x93, 0x9a, 0x79,
	0x03, 0x76, 0x06, 0xa3, 0x23, 0xd7, 0x73, 0x83, 0x10, 0x0f, 0x42, 0x1f, 0x5b, 0x86, 0xfd, 0x47,
	0x1d, 0xb6, 0x87, 0x2c, 0x95, 0x8f, 0x83, 0xba, 0x72, 0xe8, 0x73, 0xe8, 0x44, 0x15, 0x5c, 0xb6,
	0x64, 0xc5, 0x8a, 0xee, 0xc3, 0x8d, 0xaa, 0x25, 0x4c, 0xc4, 0xa4, 0x60, 0xc7, 0xfa, 0x82, 0xa4,
	0xc2, 0x8c, 0x71, 0xc1, 0x49, 0x22, 0x4e, 0x78, 0xa1, 0x53, 0x55, 0x13, 0xea, 0x03, 0x9a, 0xa7,
	0x9c, 0x92, 0xf8, 0x48, 0x8b, 0xe8, 0x90, 0xcd, 0x53, 0xa1, 0x3a, 0xb3, 0x89, 0xaf, 0x58, 0x91,
	0x93, 0x49, 0xb2, 0x90, 0xcd, 0x54, 0x77, 0x9a, 0x58, 0x03, 0x34, 0x84, 0x9d, 0x09, 0x11, 0x34,
	0x13, 0xf9, 0xde, 0xfc, 0x85, 0xb9, 0xa2, 0x77, 0xc3, 0xd7, 0xa4, 0xd8, 0x84, 0x97, 0x7d, 0x64,
	0xe8, 0x98, 0x93, 0x73, 0xa1, 0x44, 0xae, 0x85, 0x35, 0x40, 0xdf, 0x83, 0xb5, 0x74, 0xae, 0xcb,
	0x19, 0x55, 0x5a, 0xd6, 0xd9, 0xdf, 0xbb, 0x52, 0x13, 0xca, 0x9d, 0x4b, 0x40, 0xba, 0xe1, 0xb5,
	0x40, 0x88, 0x00, 0x92, 0x14, 0x3f, 0x4f, 0xb4, 0xf0, 0xe9, 0xb7, 0x46, 0xc9, 0x61, 0x67, 0xff,
	0xab, 0x8f, 0x84, 0xf7, 0xd6, 0x1c, 0xf1, 0x15, 0xc1, 0xec, 0x87, 0x60, 0xad, 0x16, 0x52, 0xa1,
	0x46, 0x1b, 0x1a, 0xc7, 0xd8, 0x7d, 0x39, 0x08, 0xa5, 0xb0, 0xb6, 0x60, 0xf3, 0x00, 0xfb, 0x27,
	0xc7, 0x96, 0x69, 0x3f, 0x04, 0xb4, 0x1e, 0x5f, 0x2a, 0xaf, 0xe7, 0x87, 0xee, 0xb3, 0xef, 0xac,
	0x0d, 0x84, 0xa0, 0x33, 0xf2, 0x5f, 0x49, 0x7d, 0x1e, 0xb9, 0x41, 0x78, 0x82, 0x9f, 0x5a, 0x86,
	0xfd, 0x8b, 0x01, 0x3b, 0xe5, 0xb4, 0xa6, 0x53, 0x96, 0xca, 0x07, 0x2c, 0x7f, 0x1d, 0x4b, 0x46,
	0x2d, 0x0c, 0x92, 0x1e, 0x5a, 0x37, 0x62, 0x75, 0x1f, 0x4c, 0x75, 0x1f, 0xaa, 0x26, 0x64, 0xc3,
	0x76, 0x92, 0x79, 0x94, 0xc6, 0x98, 0x4e, 0x93, 0x54, 0x0b, 0x6a, 0x13, 0x2f, 0xd9, 0x2a, 0x72,
	0x5b, 0x5f, 0x92, 0xdb, 0xf7, 0x35, 0x68, 0x57, 0xc6, 0x8d, 0x1e, 0xc1, 0x56, 0xa4, 0xaa, 0xca,
	0xdf, 0x84, 0x2b, 0x34, 0x7d, 0xa9, 0x78, 0x9c, 0x6f, 0x97, 0x77, 0x56, 0x10, 0x3e, 0xa6, 0x32,
	0x85, 0xa6, 0x7a, 0x89, 0xe5, 0x9a, 0xe4, 0x68, 0x45, 0x0a, 0x4b, 0x8c, 0x9e, 0x03, 0x64, 0x34,
	0x15, 0xf9, 0x54, 0xf5, 0xaf, 0x53, 0xef, 0x5a, 0x4a, 0xf6, 0x83, 0x72, 0x3f, 0xae, 0xf8, 0xa2,
	0x10, 0x3a, 0x9c, 0x46, 0x34, 0xb9, 0xa0, 0x71, 0x1e, 0x6d, 0x53, 0x45, 0xbb, 0x7f, 0x7d, 0x34,
	0xbc, 0xe4, 0x83, 0x57, 0x62, 0xd8, 0x7b, 0x00, 0x8b, 0x7c, 0x92, 0x0a, 0x81, 0xe3, 0x8d, 0x5c,
	0xef, 0xc0, 0xda, 0x50, 0x6f, 0xec, 0xc0, 0x3d, 0x74, 0xe4, 0x5f, 0x54, 0x13, 0xea, 0xd8, 0x19,
	0x8c, 0x2c, 0xd3, 0xee, 0x43, 0x67, 0x39, 0x24, 0xda, 0x86, 0x26, 0x76, 0x86, 0x8e, 0xfb, 0xd2,
	0x19, 0x59, 0x1b, 0xa8, 0x03, 0x30, 0xf2, 0x4f, 0xbd, 0x43, 0x7f, 0x30, 0x92, 0x9e, 0xf6, 0x17,
	0x60, 0xe5, 0xa5, 0x8c, 0x12, 0x4e, 0x23, 0x25, 0x34, 0x4d, 0xa8, 0xcb, 0x34, 0x9a, 0x7b, 0xb9,
	0xaf, 0x65, 0xd8, 0x7f, 0x9a, 0xf0, 0x9f, 0xfc, 0x6d, 0xf4, 0x67, 0x94, 0x2b, 0xd6, 0xfd, 0xeb,
	0xc1, 0x39, 0xd0, 0x11, 0x3c, 0x19, 0x8f, 0x17, 0x9a, 0x6a, 0x7e, 0x8a, 0xa6, 0xae, 0x38, 0x49,
	0x12, 0x93, 0x38, 0xc6, 0x94, 0x64, 0x2c, 0xcd, 0x35, 0x6c, 0x61, 0x90, 0x14, 0xe5, 0xf4, 0x0d,
	0x95, 0x6f, 0xba, 0xda, 0xa0, 0x49, 0xb8, 0x64, 0x43, 0x2f, 0xa0, 0x2e, 0xa4, 0x70, 0xe8, 0xa9,
	0x3d, 0xfa, 0xe0, 0xcf, 0xc4, 0xea, 0xd1, 0xfb, 0xa5, 0x41, 0x09, 0x88, 0x0a, 0x62, 0x7f, 0x0d,
	0x3b, 0x4b, 0x66, 0xdd, 0xc8, 0x6f, 0x4f, 0x9c, 0x20, 0xd4, 0x93, 0x1b, 0x0c, 0x87, 0xce, 0x71,
	0xa8, 0xff, 0x94, 0xb0, 0xf3, 0x8d, 0x33, 0x0c, 0x2d, 0x53, 0x7e, 0x8f, 0x9c, 0x43, 0x27, 0x74,
	0xac, 0x9a, 0xdd, 0x86, 0x96, 0x33, 0x9d, 0x89, 0x4b, 0xf9, 0x07, 0xfc, 0xd4, 0x3c, 0x36, 0xce,
	0xb6, 0x54, 0x19, 0x0f, 0xfe, 0x0e, 0x00, 0x00, 0xff, 0xff, 0xa4, 0x8d, 0x70, 0x8c, 0xb4, 0x0c,
	0x00, 0x00,
}
